services:
  crypto-coingecko:
  image: project-crypto-coingecko:0.0.1
  build:
    context: ./project-crypto-coingecko
    dockerfile: Dockerfile
  ports:
  Docker Desktop
  
  Dockerize Spring Boot A...
  1crypto-polygon:
  image: project-crypto-polygon:0.0.1
  Docker Commands
  build:
  
  Docker Compose
  dockerfile: Dockerfile
  Jmeter
  ports:
  8185:8085
  context: ./project-crypto-polygon
  8186:8086