FROM openjdk:17
LABEL maintainer="benng512@gmail.com"
ADD target/bc-xfin-service-0.0.1-SNAPSHOT.jar bc-xfin-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","bc-xfin-service-0.0.1-SNAPSHOT.jar"]
EXPOSE 8101